[[manager.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = "T"
run = "plugin hide-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
on = "M"
run = "plugin mount"
