[opener]
edit = [{ run = 'nvim "$@"', block = true, for = "unix" }]

[manager]
show_hidden = true

[plugin]
append_previewers = [
  { name = "*.md", run = "mdcat" },
  { name = "*", run = "hexyl" },
]
