"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[opener]
edit = [{ run = 'nvim "$@"', block = true, for = "unix" }]

[manager]
show_hidden = true

[plugin]
prepend_previewers = [{ name = "*.md", run = "mdcat" }]
append_previewers = [{ name = "*", run = "hexyl" }]
